### ISSUE TITLE
Meta + backslash shortcut won't survive a reboot.

### ISSUE THREAD

**Issue by Lupccs** [lxqt/lxqt-globalkeys#121]
Hello everybody and thanks for the great job you’re doing on this DE!

I'm trying to set up a shortcut where pressing Meta+backslash brings out featherpad (but I also tried kcalc just to check, and it would behave the same way)
I do manage to assign this shortcut through lxqt-globalkeys, which works properly until I reboot. after the reboot, it won't work anymore: the shortcut doesn't load anything. Meta+u, for example, works perfectly, only Meta+backslash won't survive a reboot even though it still appears among lxqt-globalkeys shortcuts (and not in bold)
Meta+backslash also works smoothly when I set it through openbox

I'm using Lubuntu 19.04 with all the latest updates

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* liblxqt Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
I tested with the Debian Buster ISO that I'd installed on VirtulBox weeks ago and `Meta+backslash` worked without problem before and after reboot.

Your problem may be an ambiguous shortcut, which is defined in more than one place.
