### ISSUE TITLE
feature request: improved restart handling

### ISSUE THREAD

**Issue by wxl** [lxqt/lxqt-globalkeys#124]
It would be nice if there were options to restart and/or reconfigure a running daemon. 

##### Expected Behavior
It's easy to restart `lxqt-globalkeysd`.

##### Current Behavior
It's not easy to restart `lxqt-globalkeysd`.

##### Possible Solution
With Openbox, for example, you can run `openbox --restart` to stop the current daemon and start a new one or you can run `openbox --reconfigure` after having edited the configuration files to get the running daemon to use them. Alternately, sending `SIGHUP` or `SIGUSR` might work.

##### Context
The primary issue is that in order to ensure the daemon is run in the same fashion, one would have to research how the daemon was run in the first place and to replicate it, rather than the above suggestions which would work universally for everyone and could be documented in the `man` page.

##### System Information
* Distribution & Version: Lubuntu 19.10
* Kernel: 5.0.0
* Qt Version: 5.12.2
* liblxqt Version: 0.14.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by tsujan** [comment]
> It's not easy to restart lxqt-globalkeysd.

It's a piece of cake (→ LXQt Session Settings).

**Comment by wxl** [comment]
I stand corrected! I completely forgot about that. I'm amazed when things are so simple and useful. Good job, ya'll!
