### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ramansarda2000** [lxqt/lxqt-globalkeys#130]
Hii.
Do you plan to have a new release soon? About using xdg-hierarchy if no config file is given. It would be great if you could provide a release. We won't have to patch it for lubuntu then. It actually affects a high priority task on our end so I wanted to know if new release was upcoming.

Thanks!

**Comment by wxl** [comment]
It would be really great to have this before 22 August when our FeatureFreeze is.

**Comment by tsujan** [comment]
> ... before 22 August

@agaida usually considers much more things than I do but, considering several PRs that should still be reviewed, more PRs that will come, and the time needed for testing after all changes are made. I really doubt that it'll be possible..

**Comment by ramansarda2000** [comment]
I tried patching the latest commit to the latest release. The patch didn't apply. Could you please guide us on how we should patch the latest release so that the improvements brought by last commit are reflected in latest release ?

**Comment by tsujan** [comment]
For each LXQt component, track the latest git backward to the latest release; you'll see all patches. Skipping any of them could have serious consequences. But I don't get it: if you should apply all patches, why not using the latest git version?

**Comment by agaida** [comment]
@tsujan: Pretty easy - Lubuntu has deadlines - we not. And i promised to release lxqt-globalkeys if ready and maybe others before their freeze - to prevent patches on their side. It will be a win/win - we release if possible, it will land in sid, if sane it will downstreamed five days later, nobody has to patch it downstream - meaning: 
* if it don't work it is easier to track down
* no bad surprises (aka not fully patched)
* it is  nice move of ours and it's also nice that the Lubuntu guys ask instead of wild patching :smile:

The only con i see in a bug @wxl wrote - our globalkeys enumeration. Really insane, if possible we should remove the enumeration and handle it database-like with the command as primary key (not perfect, but a good start) - had to test the current behaviour, it would make absolutely no sense if the config is read from /usr/share, /etc/xdg and somewhere and the result would be duplicated entries in the keymap because of enumeration - will test it friday/sunday. Otherwise i see no problem.

**Comment by agaida** [comment]
Hmm - anyways - lxqt-globalkeys is the last component which has configurations not in /usr/share so _*all*_ distributions will have a hard time to provide own configurations.

**Comment by tsujan** [comment]
@agaida OK.

I just wanted to say that I see several problems here and there and they're more than what I could fix in such a short time.

On the other hand, once I fix all problems that I see, I start to see more -- that's the case everywhere, not just in LXQt. So, what could I say? ;)

BTW, I think lxqt-archiver will be ready for its first release after current patches -- and, maybe, a few more patches -- are applied. Its remaining issues could be reported by users.

**Comment by agaida** [comment]
i see lxqt-archiver being release ready too soon - before i forget: Try to open a deb file. Other archivers do it without problems - it was not possible with lxqt-archiver without glitches (reason might be that a debian package is more or less a combiantion of two tar archives with maybe different compressions inside, can be, not a must) - and i would release it even if it is not perfect, thats why sombody has invented the "Known issues" section.

Back to topic - @palinek's patches enable us to move our configs to /usr/share - if this will introduce new problems, bad luck - as they are there before like in merging /etc/xdg and ~/.config/lxqt/ - but maybe these flaws become more clear now. Please give me two day of time, can test at weekend, not before. Reason: Google for 'GOC Germay Stuttgard' the biggest yearly dance sport event in Germany - and the company i work for is a supplier. So hard times for me this week :D

**Comment by agaida** [comment]
@wxl - you want it, you get it - it will not be worse than before, but please don't complain afterwards :D 
//me crawl away and hides

**Comment by tsujan** [comment]
> Try to open a deb file.

Should download some, being on Manajro. Thanks for the fast report (I might open a detailed one).

**Comment by agaida** [comment]
To be honest - i've not tested it lately - and i would like to see it as a corner case - ok, it might be important for Debian and Debian derivatives, but i guess that no normal user will ever use it. And to be honest - in this case i would don't care of developers, they should be able to file a senseful bug and/or provide patches. It is far enough if the first released version don't wreck any user datas - and thats still the case (to my knowledge) today. 

And i'm serious about: User data are the most sensible things we handle - i don't care about special formats - if lxqt-archiver shows crap or segfault - not nice, but anyways, no real harm happend. If a user use lxqt-archiver to compress data in our supported formats and will lose them i would go ballistic.

**Comment by tsujan** [comment]
LOL! I may not see the wood for the trees but I'm sure it's much better than what you described ;) After all, its engine is that of file-roller and engrampa.

**Comment by wxl** [comment]
I think the XDG compliance will be a huge plus and a big checkbox in general for the entire LXQt project. Thanks for pushing this through! It will really make some things we want to do possible.

That said, I'm not sure I can guarantee there will not be constructive criticism in the future :rofl: but always towards the goal of improving LXQt.

Re: unarchiving deb files, I wouldn't sweat it too much. `unar` magically handles it (one step at a time, though) but that's a really rare exception. I know no one that wants to crack open one of those unless they are an advanced user. And if that's what they are, they probably know enough to go look up the spec and use `ar` and `tar` appropriately. Such a non-issue.

**Comment by tsujan** [comment]
> I'm not sure I can guarantee there will not be constructive criticism in the future

Constructive or not constructive, they're welcome. I'll exercise my right to agree or disagree ;)

**Comment by agaida** [comment]
@wxl: that was one of the first things i tried - and i guess that i'm not alone. Beside of this: @tsujan   
* apt download lxqt-about
* open in file-roller or engrampa and lxqt-archiver - if no difference, well done

:D - hmm, i should really hide now :D

**Comment by agaida** [comment]
More serious: @wxl - the configuration problem of lxqt-globalkeys is solved, but the bug you wrote is not handled yet - we both know the drill - so if we can deliver it better we will.

**Comment by tsujan** [comment]
Ha ha... I downloaded `libfm-qt6_0.14.1-9_amd64.deb`, `libfm-qt-dev_0.14.1-9_amd64.deb` and `lxqt-about_0.14.1-1_amd64.deb`. The lxqt-archiver I have (with the patches in the latest PRs) correctly extracts them, shows their control and data archives, and correctly extracts those archives too. No issue to open.

Just `application/vnd.debian.binary-package` should be added to https://github.com/lxqt/libfm-qt/pull/454 for lxqt-archiver; will do it tomorrow.

Arqiver is a little cleaner because it always extracts files into a clean folder -- I made it so because I was tired of seeing multiple files among others after extraction. I might add that property to lxqt-archiver later (as an option?).

**Comment by agaida** [comment]
Wow, cool - Linux is about alternatives - and we should release arqiver too - just to see the fanboys fight - sorry, can't be serious today. And some month later we should tell them that both applications are by the same author. :sunglasses:

**Comment by tsujan** [comment]
> open in file-roller or engrampa and lxqt-archiver

Engrampa:

![engrampa](https://user-images.githubusercontent.com/981076/62666543-167df880-b999-11e9-8e67-f9901084f0e2.png)

lxqt-archiver:

![lxqt-archiver](https://user-images.githubusercontent.com/981076/62666555-1ed63380-b999-11e9-85ce-2e9ec6303d2f.png)

Are you sure that you used lxqt-archiver?!

**Comment by wxl** [comment]
@agaida I think that whole mess is messy, but it's not going to stop us in our tracks. If it can be solved simply and easily, great, but I don't think it should hold us up from a release. 

Also, being from '77, the Henry Rollins I know was in a band called Black Flag…
[![black flag/coffee](http://img.youtube.com/vi/i4odD2Bg1_0/0.jpg)](http://www.youtube.com/watch?v=i4odD2Bg1_0 "Black Flag - Black Coffee")
https://www.youtube.com/watch?v=i4odD2Bg1_0

**Comment by tsujan** [comment]
> i was born 1969 ....  being from '77

OK, I knew I was the oldest but will keep my secret ;)

**Comment by agaida** [comment]
Ok, i'm forced to do this now. A statement borrowed from an mostly unknown folk singer:
https://www.youtube.com/watch?v=9FcrGs_7XD0 - we can discuss every thing except bullshit - and there is a built in problem - who decide if anything is bullshit? So: Let's be verbose, not every harsh answer means a hard "No!"-  But it might be that we must convinced that the bug/feature request/anything else is helpful and will help our users. Even if we don't get it at a first glance.

RIP Lenny and look forward: Let's rock

**Comment by wxl** [comment]
"Unknown folk singer!" You're killing me, @agaida 🤣

However it is objectively bullshit that Hawkwind got rid of Mr. Kilmister.
https://youtu.be/khwWrGhVNvI

And @tsujan sorry if we're boring you, old man 😁

**Comment by ramansarda2000** [comment]
> Back to topic - @palinek's patches enable us to move our configs to /usr/share - if this will introduce new problems, bad luck - as they are there before like in merging /etc/xdg and ~/.config/lxqt/ - but maybe these flaws become more clear now. Please give me two days of time, can test at weekend, not before. 

Did you have time to test?

**Comment by agaida** [comment]
Done

**Comment by ramansarda2000** [comment]
Thanks!
