### ISSUE TITLE
change .desktop icon of lxqt-config-globalkeyshortcuts to "preferences-desktop-keyboard-shortcuts"

### ISSUE THREAD

**Issue by hmollercl** [lxqt/lxqt-globalkeys#131]
The current icon "preferences-desktop-keyboard" is more general than "preferences-desktop-keyboard-shortcuts" which is exactly for what globalkeysshortcuts is for.

**Comment by tsujan** [comment]
`preferences-desktop-keyboard-shortcuts` is rather for GTK apps. It doesn't exist in Breeze or Oxygen.

**Comment by wxl** [comment]
@hmollercl do you have another candidate that is within Breeze or Oxygen?

**Comment by hmollercl** [comment]
no, only that about-lxqt should have their own icon, the helix.
