### ISSUE TITLE
Brightness shortcuts cannot be disabled from "Edit Action" dialog

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-globalkeys#134]
In the latest git source, there are 4 brightness shortcuts with names `☀ ↑` and `☀ ↓` (they're defined in "/usr/share/lxqt/globalkeyshortcuts.conf"). If I disable them, they'll get enabled again after restarting the daemon.

**Comment by agaida** [comment]
![](https://i.imgur.com/5C7wlaG.png)

can't reproduce right now, this is with you first patch

**Comment by tsujan** [comment]
Restart the daemon and see them re-enabled.

**Comment by tsujan** [comment]
OK, I tested: my conscience is clear ;) This bug existed before my patch. The difference is just that, before the patch, duplicate `☀ ↑` and `☀ ↓` items were created.

I think it may have something to do with the names (`☀ ↑` and `☀ ↓`).

**Comment by agaida** [comment]
ok - i encountered that disabling was possible - and the things remain enabled or disabled - the only thing is: if i delete a setting it will be there because of our xdg reading of the configurations - i thought about a delete marker or an unset in the user config sometimes, because there is no other way to prevent inherited settings

**Comment by agaida** [comment]
generally speaking for all our configurations:
* if i set something in /usr/share/lxqt/foo.conf i can
* override it in /etc/xdg,
* set it to null later

but i can't unset any setting which i ever have done before - and that sucks, esp. if some applications only ask if set.

**Comment by tsujan** [comment]
> i encountered that disabling was possible

Disabling those shortcuts is NOT possible here: they will be enabled after a daemon restart. I tested 10 times.

**Comment by agaida** [comment]
Check the rights of the files in `~/.config/lxqt` - obvious i know, but i run myself into it sometimes after i wrecked things forcefully - and forget about :smile:

**Comment by tsujan** [comment]
> obvious i know

Too obvious ;) I wonder how you can't see it! The settings are saved correctly *before* restarting the daemon. I made a backup of the config file, then restarted the daemon, then compared the backup with the new config file: `Enabled=false` was turned into `Enabled=true` for those shortcuts.

**Comment by agaida** [comment]
url: http://pb.5id.eu/FzOC.mkv
Made a short screencast - but i can't resist to say, that is works fine for me :D

**Comment by tsujan** [comment]
Frankly, I needed that the video ;) The problem got worse.

**Comment by tsujan** [comment]
Ah, found the difference in your video: You disable them by double clicking the view-item check-box, while I tried to disable them in the "Edit Action" dialog. If I use the view-item check-box, I could disable them too.

The bug is related to the dialog.

**Comment by tsujan** [comment]
Nope! Happens with the view-item too; only the first time and with a newly created config file.

**Comment by tsujan** [comment]
Found the reason. It has nothing to do with brightness shortcuts and is somehow random, as implied here.

I'm making a simple PR; the only difficult job is writing the PR comment ;)
