### ISSUE TITLE
No way to remove global shortcuts

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-globalkeys#135]
There's no way to remove the shortcuts that aren't defined by the user -- let's call them "global" -- at best, they can be disabled.

The code should allow the removal of any kind of shortcut, IMO.

**Comment by agaida** [comment]
That's the same thing as for all our configurations - we have right now no way to remove any setting from a configuration.

**Comment by tsujan** [comment]
Some of them can be removed but will return after daemon restart. It's a bug.

> we have right now no way to remove any setting from a configuration.

This is very different, IMO. It's counter-intuitive, at best. The user sees a shortcuts and removes it but he sees it again after restart.

**Comment by tsujan** [comment]
The code *at least* should disable the remove button in the case of global shortcuts if it can't remove them.

**Comment by tsujan** [comment]
@agaida 

I think this is very unprofessional because it's confusing to users: they see all shortcuts on the same level but they can remove only some of them. Technical explanations are irrelevant.

There's a simple solution: once the user config file is created and contains at least one shortcut, the daemon shouldn't read global shortcuts on future restarts. We can even add a "Restore Defaults" button.

Waiting for https://github.com/lxqt/lxqt-globalkeys/pull/136 to be decided.

**Comment by agaida** [comment]
With a restore defaults button i guess it's fine.

**Comment by tsujan** [comment]
The patch is very simple without the restore button, while the button might need a structural change. So allow me to fix this issue first. Later, I'll think about a restore button.

The restore button isn't so needed either -- although I'll try to add it -- because if the user removes *his own* shortcuts, he couldn't restore them. Moreover, if the user has doubts, he could always disable a shortcut, instead of removing it.

**Comment by tsujan** [comment]
OK, added a working "Default" button here, that removes all user-defined shortcuts and restores the default ones, by asking the user:

![default_button](https://user-images.githubusercontent.com/981076/63684700-c74a1b80-c812-11e9-9350-2c783d9b10ce.png)

**Comment by agaida** [comment]
Ok, seems ok to me - no objections after all these days
