### ISSUE TITLE
New release coming?

### ISSUE THREAD

**Issue by hmollercl** [lxqt/lxqt-globalkeys#142]
Is there a new release coming in near future? one of the problems we have we believe it might be solved with https://github.com/lxqt/lxqt-globalkeys/commit/b924f8cd41474d2fe4d8e0a6f52a131bd6f50f79 and is better to have a new release than patch it.

**Comment by tsujan** [comment]
@agaida knows it but if you want to apply patches, please apply all of them! Skipping one could have side effects.

**Comment by hmollercl** [comment]
I'm not 100% sure if we can update now or SRU it, but is a serious issue so we could ask for exception.

We have problems with runner and menu shortcuts we use Meta+R and Super_L for them. After session start they need to be stoped and start again, other option is to delete ~./config/lxqt/globalkeys.conf every time before logout to make it work. After new creation of ~./config/lxqt/globalkeys.conf it works ok the first login, then after first logout+login runner stop working, a new logout+login and panel stop working.

Es ist besser ein neues release als patchen, für jetzt oder SRU.

**Comment by tsujan** [comment]
> We have problems with runner and menu shortcuts we use Meta+R and Super_L for them. 

If that isn't fixed in the latest git LXQt, please report it!

**Comment by hmollercl** [comment]
I think https://github.com/lxqt/lxqt-globalkeys/commit/b924f8cd41474d2fe4d8e0a6f52a131bd6f50f79 solves it. But haven't checked.

**Comment by agaida** [comment]
@hmollercl - easy solution: just check it! :P - ok, i should hide again. And please not the argument: I don't  know how to do this - it's a nobrainer to create a matching debian package - ok,  one has to learn a thing or two - but it would be the beginning of a big carrer :D

**Comment by agaida** [comment]
@hmollercl - i know it sounds harsh, with a big but: And the **but** is - if you help yourself you will help maybe many others with the things that you do, so - you are in a devel team - act like a dev. We will help you in any way we could.

**Comment by hmollercl** [comment]
yes, only need to find the time to do it. Just came back from vacation and have a loooot of accumulated work. I think this weekend I could find some time.

**Comment by tsujan** [comment]
Whenever you find the time, please check it and open an issue if the problem persists. Thanks in advance!

**Comment by agaida** [comment]
first hint could be:
```
apt install devscripts debhelper lxqt.build-tools
```
the rest is just debian and derivatives magic - one will find the complete debian packaging on salsa (https;//salsa.debian.org) - if one clone the package in charge and checkout the experimental snapshots one can build the latest git of the package and install it locally using only the debian magic. should be nearly a nobrainer - and if patches would be involved it would remain a nobrainer - trust me, i'm to dump for complex things

**Comment by agaida** [comment]
sorry if i constantly say debian - it will work for smaller (lubuntu) and bigger (Extix) distributions (writing this and hide in my shelter again) :P

**Comment by hmollercl** [comment]
just fyi, also needed package liblxqt0-dev 
which also needed: libmagic-dev libqt5xdg-dev libqt5xdgiconloader-dev

**Comment by agaida** [comment]
erm - ok, i see, let's start from the very beginning - no hurry, relax, it is all done :D - cool, i feel young (40) again :D

**Comment by hmollercl** [comment]
ok, so had time and tested, latest git doesn't have the issue, so it's solved.

@agaida wird es bald ein neues Release geben?

**Comment by tsujan** [comment]
> so it's solved.

That was very good news to me. Thanks!

**Comment by tsujan** [comment]
@agaida I'm also curious about the next release. A rough estimation?

**Comment by agaida** [comment]
the answer is easy in that case - i would suggest  a point release of globalkeys - otherwise the ubuntu release team would kill us rightfully - maybe if tested enough qps tomorrow or on friday. - hope it can go into 19.10, no packaging changes needed for :smile:

**Comment by hmollercl** [comment]
good news!

**Comment by jubalh** [comment]
The Ubuntu release team should learn to create patches ;)

**Comment by tsujan** [comment]
> the answer is easy in that case - i would suggest a point release of globalkeys

No, I didn't mean globalkeys but the whole LXQt. I don't work on some ideas when we're near a release because they might need long tests.

**Comment by agaida** [comment]
Simple answer: asap

**Comment by tsujan** [comment]
> Simple answer: asap

Take you time. On second thought, I should change my habit.

**Comment by agaida** [comment]
no, you should not - but this one is a bit special - we was talking about a new release and after wie start to implement useful things like there is no tomorrow :D - we have the ability to make point releases and should use them. Esp. lxqt-globalkeys and qps was the major negative points in the review - and lxqt-globalkey are release ready and good tested (maybe not complete, but classes better as before, same for qps)

**Comment by tsujan** [comment]
> no, you should not

I won't make PRs out of those kinds of patches near a release because, like you said, "we start to implement useful things like there is no tomorrow." Even if I make a PR, I'll add: "Don't merge before vX.Y" -- theoretically speaking.

So, there is no haste on my part :)

**Comment by agaida** [comment]
done

**Comment by tsujan** [comment]
For one, I like this way of releasing.
