### ISSUE TITLE
'/etc/lxqt/globalkeyshortcuts.conf' does not work

### ISSUE THREAD

**Issue by robschi** [lxqt/lxqt-globalkeys#150]
The shortcuts config 'globalkeyshortcuts.conf' was moved from '/etc/xdg/lxqt' to '/usr/share/lxqt' in 0.14.2.
But should '/etc/lxqt/globalkeyshortcuts.conf' not also work?

For other lxqt components I have defined my global configs under '/etc/lxqt/'.

**Comment by robschi** [comment]
Sorry, I made an error, the location '/etc/lxqt/globalkeyshortcuts.conf' does work, closing...

**Comment by agaida** [comment]
@robschi - the intention was - as often stated: make it easier for distributions, admins or simple users to provide own settings - so yes, the whole XDG-Tree works.

**Comment by tsujan** [comment]
Priorities of global configs, from higher to lower: `/etc` → `/etc/xdg` → `/usr/share` (if all of them are set).
