### ISSUE TITLE
Enabling of a disabled shortcut does not take effect without a daemon restart

### ISSUE THREAD

**Issue by tsujan** [lxqt/lxqt-globalkeys#175]
##### Expected Behavior

When I enable an existing but disabled shortcut, I expect it to work.
##### Current Behavior

When a disabled shortcut is enabled, a daemon restart is needed for it to work.
##### Possible Solution

Will make a PR.
##### Steps to Reproduce (for bugs)

1. Enable a disabled shortcut or disable a working shortcut and enable it again.
2. Press the keys of that shortcut.

Then nothing will happen until you restart `lxqt-globalkeysd`.

##### Context

I found this bug while fixing https://github.com/lxqt/lxqt-globalkeys/issues/173.
##### System Information

* Latest git LXQt.

**Comment by Loader009** [comment]
I can confirm this:
I enabled two already disabled shortcuts (CTRL+F1 and CTRL+F2), it worked immediately.
But after disabling and reenabling them again, they did not work anymore.

I also cannot restart `lxqt-globalkeysd` without quitting the current session:
```
$ lxqt-globalkeysd --no-daemon
[Critical] Cannot register service 'org.lxqt.global_key_shortcuts'
[Notice] Stopped
```
(same thing happens with `--daemon` but the error message is being sent to syslog)
`Version: 0.15.0`

**Comment by Loader009** [comment]
I can confirm this:
I enabled two already disabled shortcuts (CTRL+F1 and CTRL+F2), it worked immediately.
But after disabling and reenabling them again, they did not work anymore.

Restarting `lxqt-globalkeysd` by killing it manually and run it via `lxqt-globalkeysd --daemon` gets it back up, the enabled keys work until I disable them again, with no way to get them working until I restart `lxqt-globalkeysd`.

**Comment by tsujan** [comment]
@Loader009 
I'll make a PR for it in a few minutes. Although the problem was less severe than https://github.com/lxqt/lxqt-globalkeys/issues/173, its fix wasn't as simple as that of the latter -- although it wasn't complex either.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/lxqt-globalkeys/pull/176

And thanks for confirming the report!

**Comment by Loader009** [comment]
Dunno if a confirm is needed, PR fixes this issue :)
(sidenote, you have a typo, if you care :D -> Do not **requite** daemon restart for enabling shortcuts)

**Comment by tsujan** [comment]
> Dunno if a confirm is needed

It's needed and appreciated. Being effective in one system (mine) isn't enough for a fix. Thanks!

> sidenote, you have a typo, if you care :D -> Do not requite daemon restart for enabling shortcuts

Funny typo! "R" and "T" keys are beside each other and "requite" is a word in English :) I'll correct it when updating the changelog (before releasing the next version of LXQt -- months later).
