### ISSUE TITLE
shortcut for main menu: shortcut works only half

### ISSUE THREAD

**Issue by ralf3u** [lxqt/lxqt-globalkeys#187]
in the description of the shortcut-configuration there is as default the windows-key;
the description is there: **"Show/hide main menu"**; 
the shortcut shows in fact the main menu, but it does not hide it, so it works half of the description

##### Expected Behavior
when main menu is visible: by pressing the windows-key should hide the main menu

##### Current Behavior
when main menu is visible: by pressing the windows-key the main menu is still there

##### Possible Solution
I think the intention was really: "Show/hide main menu"; but it was not programed till the end;

not only because of the description it should have this do/undo-behavior, but also because it should have the same do/undo-behavior like the mouse:
- click in the panel on the main-menu-symbol: main menu appears
- click again in the panel on the main-menu-symbol: main menu disappears

at the moment the main menu can disappear with the esc-key; for people who are used to esc, one could program something like:
if (main menu is visible) then (if esc or windows-key is pressed): hide the main menu

##### Steps to Reproduce (for bugs)
1. press the windows-key to let appear the main menu
2. press again the windows-key to hide the main menu

##### Context
shortcuts should work like the description

##### System Information
* Distribution & Version: Lubuntu 20.10
* Qt Version: 0.15.0

**Comment by rkitover** [comment]
This doesn't seem to happen anymore, the keybind for "Show/hide main menu" also hides it.

**Comment by ralf3u** [comment]
>This doesn't seem to happen anymore, the keybind for "Show/hide main menu" also hides it.

I can not confirm in Lubuntu 22.04 with LXQt 0.17.0. But it can be that it is fixed in LXQt 1.1.0.

**Comment by ralf3u** [comment]
>This doesn't seem to happen anymore, the keybind for "Show/hide main menu" also hides it.

I can confirm in Lubuntu 22.10 with LXQt 1.1.0 that the issue was fixed.
