### ISSUE TITLE
Unlock valid shortcuts

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-globalkeys#219]
The UI doesn't allow for certain valid shortcuts (e.g. I have mapped `Meta-E` to `xdg-open /home/<user>`). This likely will hit quite a number of systems since 0.17 deactivates `lxqt-openbox.conf` - forcing users to manually "reconfigure" openbox and LXQt shortcuts.

LXQt should solve that during upgrade (0.17.1 package maybe?). E.g. rename an existing `~/.config/openbox/lxqt-openbox.xml` to `…/rc.xml` when upgrading.

##### Expected Behavior
User can define shortcuts for any key combination.

##### Current Behavior
Some shortcuts including the `Meta` key cannot be registered via UI (dialog with 10s countdouwn). They do work however, so for example adding this to the config helps:

```ini
[Meta%2BE.26]
Comment=File Manager
Enabled=true
Exec=xdg-open, /home/<USER-NAME>

```

:bulb: Don't forget to replace sequence number (26 here) and <USER-NAME> with local settings!

##### Steps to Reproduce (for bugs)
Try to register a `Meta-E` shortcut via lxqt-globalkeys UI.

##### Context
Desktop environment

##### System Information
Affects any LXQt 0.17 setup

**Comment by tsujan** [comment]
Not reproducible. The Meta modifier can be used to create shortcuts.

**Comment by antis81** [comment]
Mmh… retried it today and now it worked… Guess it was "eaten away" by another process then.
