### ISSUE TITLE
feature request: filter shortcuts

### ISSUE THREAD

**Issue by antis81** [lxqt/lxqt-globalkeys#225]
##### Expected Behavior
A possibility to filter the list by the fields "shortcut", "description" and "info".

##### Current Behavior
Not implemented

##### Possible Solution
Add a text field where a contained string can be entered.

##### Steps to Reproduce (for bugs)
n.a.

##### Context
Improve usability

##### System Information
* Package version: 0.17

**Comment by tsujan** [comment]
Seems acceptable to me. Whether it'll be worth the effort, I don't know — the user can already sort the list in different ways.

We accept and review patches.

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/lxqt-globalkeys/pull/226
